"""Phase 4: build data/eye_drive.json, which Godot uses to turn a rendered view into
per-photoreceptor spike rates for the real FlyWire neurons.

Inputs: data/ommatidia.json, data/ommatidia_placement.json, data/raw/Completeness_783.csv
(its row order is the neuron index used by the GPU brain).

Vision is rendered as a cube map (6 x 90 deg cameras) centred between the two eyes, parented to
the head. Each facet samples a Gaussian acceptance cone, FWHM 5 deg (literature; Gonzalez-Bellido
et al. 2011), from that cube. Approximation: one viewpoint for both eyes ignores the ~0.6 mm
parallax between them (negligible except for objects within a few mm).

Coordinates here are Godot head-local: glTF converts FlyGym/Blender (x anterior, y left, z dorsal)
to (x, z, -y), so anterior = +X, dorsal = +Y, left = -Z.
"""
import json, pathlib
import numpy as np, pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[1]
N = 48                        # pixels per cube face edge (1.9 deg/pixel at face centre)
FWHM = 5.0
SIG = np.radians(FWHM / 2.3548)
CUT = 2.5 * SIG

# spectral channel per photoreceptor (approximate: RGB render stands in for fly opsins)
# 0 = luminance (R1-6, Rh1 broadband), 1 = blue as UV stand-in (R7: Rh3/Rh4),
# 2 = blue (pale R8: Rh5), 3 = green (yellow R8: Rh6)
def channel(t, subtype):
    if t == "R1-6":
        return 0
    if t == "R7":
        return 1
    return 2 if subtype in ("pale", "DRA") else 3


def to_godot(v):
    v = np.asarray(v, float)
    return np.stack([v[..., 0], v[..., 2], -v[..., 1]], -1)


# cube faces: (forward, right, up) in Godot head-local coords
FACES = [
    ((1, 0, 0), (0, 0, 1), (0, 1, 0)),     # anterior, right = +Z (fly's right)
    ((-1, 0, 0), (0, 0, -1), (0, 1, 0)),   # posterior
    ((0, 0, -1), (1, 0, 0), (0, 1, 0)),    # left
    ((0, 0, 1), (-1, 0, 0), (0, 1, 0)),    # right
    ((0, 1, 0), (0, 0, 1), (-1, 0, 0)),    # dorsal
    ((0, -1, 0), (0, 0, 1), (1, 0, 0)),    # ventral
]


def pixel_dirs():
    c = (np.arange(N) + 0.5) / N * 2 - 1
    u, v = np.meshgrid(c, c)            # u: column (right), v: row (0 = top)
    dirs, solid = [], []
    for f, r, up in FACES:
        f, r, up = map(np.array, (f, r, up))
        d = f[None, None] + u[..., None] * r + (-v)[..., None] * up
        n = np.linalg.norm(d, axis=-1, keepdims=True)
        dirs.append(d / n)
        solid.append((1.0 / n[..., 0] ** 3))   # pixel solid angle ~ 1/(1+u^2+v^2)^1.5
    return np.concatenate([x.reshape(-1, 3) for x in dirs]), np.concatenate([s.reshape(-1) for s in solid])


def main():
    om = json.loads((ROOT / "data/ommatidia.json").read_text())
    pl = {p["id"]: p for p in json.loads((ROOT / "data/ommatidia_placement.json").read_text())["facets"]}
    comp = pd.read_csv(ROOT / "data/raw/Completeness_783.csv", index_col=0)
    index = pd.Series(np.arange(len(comp)), index=comp.index.astype(np.int64))

    P, W = pixel_dirs()
    facets = om["facets"]
    centre = to_godot(np.mean([pl[f["id"]]["pos_head_mm"] for f in facets], 0))
    k_ptr, k_pix, k_w = [0], [], []
    pr_ptr, pr_neuron, pr_chan = [0], [], []
    dirs, sides = [], []
    lamina = {t: [] for t in ("L1", "L2", "L3", "L4", "L5")}
    missing = 0
    for f in facets:
        d = to_godot(pl[f["id"]]["dir_head"]); d /= np.linalg.norm(d)
        ang = np.arccos(np.clip(P @ d, -1, 1))
        m = np.where(ang < CUT)[0]
        w = np.exp(-ang[m] ** 2 / (2 * SIG ** 2)) * W[m]
        w /= w.sum()
        k_pix += m.tolist(); k_w += w.round(6).tolist(); k_ptr.append(len(k_pix))
        for t, ids in f["neurons"].items():
            if t in ("R1-6", "R7", "R8"):
                for rid in ids:
                    if int(rid) in index.index:
                        pr_neuron.append(int(index[int(rid)])); pr_chan.append(channel(t, f["subtype"]))
                    else:
                        missing += 1
            elif t in lamina:
                lamina[t] += [int(index[int(r)]) for r in ids if int(r) in index.index]
        pr_ptr.append(len(pr_neuron))
        dirs.append(d.round(5).tolist()); sides.append(f["side"])
    # all columnar optic-lobe neurons (both optic lobes) except photoreceptors, by type: these are
    # graded-potential cells in the real fly; Godot can give them a resting bias (approximate)
    cols = pd.read_csv(ROOT / "data/raw/column_assignment.csv.gz")
    cols = cols[~cols.type.isin(["R7", "R8", "L1", "L2", "L3", "L4", "L5"])]
    columnar = {t: [int(index[r]) for r in g.root_id if r in index.index] for t, g in cols.groupby("type")}
    out = {
        "note": "Generated by tools/build_eye_drive.py. Cube map + per-facet Gaussian acceptance "
                "cones -> per-photoreceptor Poisson rates (see README).",
        "cube_px": N, "fwhm_deg": FWHM,
        "cube_centre_head": [round(float(c), 5) for c in centre],   # Godot head-local, glTF units (mm)
        "faces": FACES,
        "n_facets": len(facets), "facet_dir": dirs, "facet_side": sides,
        "k_ptr": k_ptr, "k_pix": k_pix, "k_w": k_w,
        "pr_ptr": pr_ptr, "pr_neuron": pr_neuron, "pr_chan": pr_chan,
        "lamina": lamina,
        "columnar": columnar,
        "basis": {"cone_sampling": "literature (5 deg FWHM)",
                  "phototransduction": "approximate (graded photoreceptors as adapting Poisson rates)",
                  "spectral": "approximate (RGB render; blue stands in for UV)",
                  "viewpoint": "approximate (one cube map between the eyes)"},
    }
    (ROOT / "data/eye_drive.json").write_text(json.dumps(out))
    taps = np.diff(k_ptr)
    print(f"{len(facets)} facets, taps/facet median {int(np.median(taps))}, "
          f"{len(pr_neuron)} photoreceptor inputs ({missing} ids not in model), "
          f"lamina " + ", ".join(f"{t}={len(v)}" for t, v in lamina.items()))


if __name__ == "__main__":
    main()
